Fix multi-platform build docker error (#911)
Fix multi-platform build docker error.

See MCM comments for full context:
https://mcm.amazon.dev/cms/MCM-112315558/execution/step/9de5087f-2c46-42b8-b760-a9ce99b569df

```
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-multi-platform/
```

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.