Fix Trace Context extraction from Lambda Context object by bypassing Muzzle Check (#1218)
*Issue #, if available:*
-
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/17954879038/job/51066448865

AWS Lambda Environment may or may not have the `getXrayTraceId` method
in Lambda Context (from Lambda Core dependency). This will cause OTel's
Muzzle Check to disable the AWS Lambda Instrumentation in the event that
it isn't present, causing no Lambda Function Handler Span to appear

Fix of previous PR:
https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1191

*Description of changes:*
- Use `@NoMuzzle` annotation when accessing `getXrayTraceId` in Lambda
Context Object, which avoids OTel's muzzle check. If `NoSuchMethodError`
is caught, we do not try this logic again.
- Add unit test for when `getXrayTraceId` throws `NoSuchMethodError`.

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.